# kafka_config.py
KAFKA_BOOTSTRAP_SERVERS = 'localhost:9092'  # or your remote broker address
KAFKA_SECURITY_PROTOCOL = 'PLAINTEXT'
KAFKA_SASL_MECHANISM = 'PLAIN'
KAFKA_SASL_USERNAME = 'admin'
KAFKA_SASL_PASSWORD = '1234'


'''KAFKA_BOOTSTRAP_SERVERS = 'pkc-w77k7w.centralus.azure.confluent.cloud:909cls2'
KAFKA_SECURITY_PROTOCOL = 'PLAINTEXT'
KAFKA_SASL_MECHANISM = 'PLAIN'
KAFKA_SASL_USERNAME = 'BHGH5GP6T5ERDQLI'
KAFKA_SASL_PASSWORD = 'D40AFZISgQBVgbFh617ZBMOSkGw0FU77GFr3HBsHLbqAkXJqvl+b/LSEMfP/wXl1'
'''