# kafka_config.py
KAFKA_BOOTSTRAP_SERVERS = 'localhost:9092'  # or your remote broker address
KAFKA_SECURITY_PROTOCOL = 'PLAINTEXT'
KAFKA_SASL_MECHANISM = 'PLAIN'
KAFKA_SASL_USERNAME = 'admin'
KAFKA_SASL_PASSWORD = '1234'
